version: '3.2'
services:
    server:
        container_name: cryptic_game_server_debug
        image: useto/cryptic-game-server:experimental
        restart: always
        environment:
            MSSOCKET_HOST: '0.0.0.0'
            MSSOCKET_PORT: 1239
            WEBSOCKET_HOST: '0.0.0.0'
            WEBSOCKET_PORT: 80
            HTTP_PORT: 8080
            AUTH_ENABLED: 'true'
            STORAGE_LOCATION: 'data/'
            PRODUCTIVE: 'false'
        ports:
            - "8080:8080"
            - "80:80"
        volumes:
            - type: 'bind'
              source: './data/server'
              target: '/app/data'
        networks:
            - frontend
            - backend
    ms_device:
        container_name: cryptic_device_debug
        image: useto/cryptic-device:experimental
        restart: always
        depends_on:
            - server
        environment:
            SERVER_HOST: 'server'
            SERVER_PORT: 1239
            MODE: 'debug'
            STORAGE_LOCATION: 'data/'
        volumes:
            - type: 'bind'
              source: './data/ms/device'
              target: '/app/data'
        networks:
            - backend
    ms_currency:
        container_name: cryptic_currency_debug
        image: useto/cryptic-currency:experimental
        restart: always
        depends_on:
            - server
        environment:
            SERVER_HOST: 'server'
            SERVER_PORT: 1239
            MODE: 'debug'
            STORAGE_LOCATION: 'data/'
        volumes:
            - type: 'bind'
              source: './data/ms/currency'
              target: '/app/data'
        networks:
            - backend
    ms_service:
        container_name: cryptic_service_debug
        image: useto/cryptic-service:experimental
        restart: always
        depends_on:
            - server
        environment:
            SERVER_HOST: 'server'
            SERVER_PORT: 1239
            MODE: 'debug'
            STORAGE_LOCATION: 'data/'
        volumes:
            - type: 'bind'
              source: './data/ms/service'
              target: '/app/data'
        networks:
            - backend
networks:
    frontend:
    backend:
