version: '3.1'
services:
    server:
        container_name: cryptic_game_server
        image: useto/cryptic-game-server
        restart: always
        environment:
            MSSOCKET_HOST: '127.0.0.1'
            MSSOCKET_PORT: 1239
            WEBSOCKET_HOST: '0.0.0.0'
            WEBSOCKET_PORT: 80
            HTTP_PORT: 8080
            AUTH_ENABLED: 'true'
            STORAGE_LOCATION: 'data/'
        ports:
            - "8080:8080"
            - "80:80"
        volumes:
            - './data/server/:/data/'
        networks:
            - frontend
            - backend
    ms_device:
        container_name: cryptic_device
        image: useto/cryptic-device
        restart: always
        depends_on:
            - server
        environment:
            MSSOCKET_HOST: 'server'
            MSSOCKET_PORT: 1239
            STORAGE_LOCATION: 'data/'
        volumes:
            - './data/ms/device/:/data/'
        networks:
            - backend
    ms_currency:
        container_name: cryptic_currency
        image: useto/cryptic-currency
        restart: always
        depends_on:
            - server
        environment:
            MSSOCKET_HOST: 'server'
            MSSOCKET_PORT: 1239
            STORAGE_LOCATION: 'data/'
        volumes:
            - './data/ms/currency/:/data/'
        networks:
            - backend
    ms_service:
        container_name: cryptic_service
        image: useto/cryptic-service
        restart: always
        depends_on:
            - server
        environment:
             MSSOCKET_HOST: 'server'
             MSSOCKET_PORT: 1239 
             STORAGE_LOCATION: 'data/'
        volumes:
            - './data/ms/service/:/data/'
        networks:
            - backend
networks:
    frontend:
    backend:
